### ISSUE TITLE
Compatability with R versions >4.0 

### ISSUE THREAD

**Issue by Gauldblimey-Jet** [dbspitz/migrateR#13]
Hi, 

I've been trying to install and run the migrateR package with R version 4.0.5 (2021-03-31) however whenever I do I get the following error: 

"Warning in install.packages :
  package ‘migrateR_1.0.9.tar.gz’ is not available for this version of R

A version of this package for your version of R might be available elsewhere"  

This happens whether I use install.packages, install_github or try to install from the .gz. 

Can you advise on how to run this on newer versions of R please? 

Thanks,

Jethro

**Comment by abfleishman** [comment]
I was able to install it with 
```
devtools::install_github("dbspitz/migrateR/migrateR")
```

Looks like it had been moved to an additional folder inside the repo so had to add the extra `migrateR`

I am running R 4.1.0

**Comment by Gauldblimey-Jet** [comment]
Thank you, that didn't work for me but there is a different error now so that's progress at least. 

Downloading GitHub repo dbspitz/migrateR@HEAD
dbspitz-migrateR-6e5c413/migrateR_1.0.4.tar.gz: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Failed to install 'migrateR' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)

**Comment by Gauldblimey-Jet** [comment]
I tried again and it now seems to work.
