### ISSUE TITLE
change plot labels?

### ISSUE THREAD

**Issue by briana-abrahms** [dbspitz/migrateR#6]
Is it possible to change the plot title and x and y labels without going into the source code?

**Comment by dbspitz** [comment]
Changing the title should be easy. The title is taken from the name of the
burst, so for simple titles you can just change the name of the burst,
e.g.,
    burst(bighorn) <- c("testing", " ", 1, 2)  # then mvmtClass(bighorn),
etc., etc.
(the second argument--a space--can be used if you need more specific
formatting, which can then be added with a separate call to "title").

Changing axis labels is trickier. Not ideal, but depending on what you
need, you could try something like
    title(xlab = "Days", col.lab = "white"); title(xlab = "Your New Label")
(The results will look cleaner if you repeat the whiteout command before
assigning a new label.)

Alternatively, the source code here isn't too involved. you'd just need to
redefine the print methods for objects of class mvmt.
This can be found by returning "plot.mvmt". The X label is defined on L24,
Y on L21.

Hope that helps. Let me know if you run into more questions.

Best,


Derek Spitz
Postdoc, UCSC
Bishop, CA
(831) 737-3120
CityOfKitesAndCrows.com <http://cityofkitesandcrows.com>
Wilmers Lab <http://wildlife.ucsc.edu> // Wittmer Lab
<http://cms.victoria.ac.nz/sbs/research/ecology-biodiversity-research/ecology-and-conservation-biology>

**Comment by briana-abrahms** [comment]
Thanks Derek!
