### ISSUE TITLE
Installation with vignette 

### ISSUE THREAD

**Issue by bklaver49** [dbspitz/migrateR#8]
I tried to install migrateR yesterday with 
install_github("dbspitz/migrateR/migrateR", build_vignettes = T)
and received error messages that htmltools

**Comment by gabezuckerman** [comment]
I was unable to install this package, after trying both devtools approach and manual approach.  
I received a warning saying it is not available for R version 3.6.0

**Comment by dbspitz** [comment]
Thanks for the email. My apologies for the delayed response. I'd like to
get to the bottom of this, but haven't been able to reproduce this issue on
my machine. would you mind running the following lines of code and sending
me the output?

    require(devtools)
  session_info()
  install_github("dbspitz/migrateR/migrateR", build_vignettes = T)
  install_github("dbspitz/migrateR/migrateR", build_vignettes = F)


Thanks!


Derek Spitz
Postdoc, UCSC
Bishop, CA
(831) 737-3120
CityOfKitesAndCrows.com <http://cityofkitesandcrows.com>
Wilmers Lab <http://wildlife.ucsc.edu> // Wittmer Lab
<http://cms.victoria.ac.nz/sbs/research/ecology-biodiversity-research/ecology-and-conservation-biology>

**Comment by bklaver49** [comment]
Derek

Thank you for the reply.  With both commands, migrateR installs, but without the vignette in both cases.  When I execute help(package=”migrateR”) I can see the commands but there is nothing under vignettes.

Here is the session_info


> session_info()
- Session info --------------------------------------------------------------------------------------------------------------------------------------------
setting  value
 version  R version 3.6.1 (2019-07-05)
os       Windows >= 8 x64
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       America/Chicago
 date     2019-10-07

- Packages ------------------------------------------------------------------------------------------------------------------------------------------------
package      * version  date       lib source
 abind          1.4-5    2016-07-21 [1] CRAN (R 3.6.0)
 ade4         * 1.7-13   2018-08-31 [1] CRAN (R 3.6.1)
 adehabitatLT * 0.3.24   2019-04-07 [1] CRAN (R 3.6.1)
 adehabitatMA * 0.3.13   2019-04-07 [1] CRAN (R 3.6.1)
 assertthat     0.2.1    2019-03-21 [1] CRAN (R 3.6.1)
 backports      1.1.5    2019-10-02 [1] CRAN (R 3.6.1)
 boot         * 1.3-23   2019-07-05 [1] CRAN (R 3.6.1)
 callr          3.3.2    2019-09-22 [1] CRAN (R 3.6.1)
 car          * 3.0-3    2019-05-27 [1] CRAN (R 3.6.1)
 carData      * 3.0-2    2018-09-30 [1] CRAN (R 3.6.0)
 cellranger     1.1.0    2016-07-27 [1] CRAN (R 3.6.1)
 CircStats    * 0.2-6    2018-07-01 [1] CRAN (R 3.6.1)
 cli            1.1.0    2019-03-19 [1] CRAN (R 3.6.1)
 crayon         1.3.4    2017-09-16 [1] CRAN (R 3.6.1)
 curl           4.2      2019-09-24 [1] CRAN (R 3.6.1)
 data.table     1.12.4   2019-10-03 [1] CRAN (R 3.6.1)
 desc           1.2.0    2018-05-01 [1] CRAN (R 3.6.1)
 devtools     * 2.2.1    2019-09-24 [1] CRAN (R 3.6.1)
 digest         0.6.21   2019-09-20 [1] CRAN (R 3.6.1)
 ellipsis       0.3.0    2019-09-20 [1] CRAN (R 3.6.1)
 forcats        0.4.0    2019-02-17 [1] CRAN (R 3.6.1)
 foreign        0.8-72   2019-08-02 [1] CRAN (R 3.6.1)
 fortunes       1.5-4    2016-12-29 [1] CRAN (R 3.6.0)
 fs             1.3.1    2019-05-06 [1] CRAN (R 3.6.1)
 glue           1.3.1    2019-03-12 [1] CRAN (R 3.6.1)
 haven          2.1.1    2019-07-04 [1] CRAN (R 3.6.1)
 hms            0.5.1    2019-08-23 [1] CRAN (R 3.6.1)
 lattice        0.20-38  2018-11-04 [2] CRAN (R 3.6.1)
 magrittr       1.5      2014-11-22 [1] CRAN (R 3.6.1)
 MASS         * 7.3-51.4 2019-03-31 [2] CRAN (R 3.6.1)
 memoise        1.1.0    2017-04-21 [1] CRAN (R 3.6.1)
 migrateR       1.0.8    2019-10-07 [1] Github (dbspitz/migrateR@5883f65)
openxlsx       4.1.0.1  2019-05-28 [1] CRAN (R 3.6.1)
 pillar         1.4.2    2019-06-29 [1] CRAN (R 3.6.1)
 pkgbuild       1.0.5    2019-08-26 [1] CRAN (R 3.6.1)
 pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 3.6.1)
 pkgload        1.0.2    2018-10-29 [1] CRAN (R 3.6.1)
 prettyunits    1.0.2    2015-07-13 [1] CRAN (R 3.6.1)
 processx       3.4.1    2019-07-18 [1] CRAN (R 3.6.1)
 ps             1.3.0    2018-12-21 [1] CRAN (R 3.6.1)
 R6             2.4.0    2019-02-14 [1] CRAN (R 3.6.1)
 Rcpp           1.0.2    2019-07-25 [1] CRAN (R 3.6.1)
 readxl         1.3.1    2019-03-13 [1] CRAN (R 3.6.1)
 remotes        2.1.0    2019-06-24 [1] CRAN (R 3.6.1)
 rio            0.5.16   2018-11-26 [1] CRAN (R 3.6.1)
 rlang          0.4.0    2019-06-25 [1] CRAN (R 3.6.1)
 rprojroot      1.3-2    2018-01-03 [1] CRAN (R 3.6.1)
 rstudioapi     0.10     2019-03-19 [1] CRAN (R 3.6.1)
 sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 3.6.1)
 sp           * 1.3-1    2018-06-05 [1] CRAN (R 3.6.1)
 testthat       2.2.1    2019-07-25 [1] CRAN (R 3.6.1)
 tibble         2.1.3    2019-06-06 [1] CRAN (R 3.6.1)
 usethis      * 1.5.1    2019-07-04 [1] CRAN (R 3.6.1)
 vctrs          0.2.0    2019-07-05 [1] CRAN (R 3.6.1)
 withr          2.1.2    2018-03-15 [1] CRAN (R 3.6.1)
 yaml           2.2.0    2018-07-25 [1] CRAN (R 3.6.0)
 zeallot        0.1.0    2018-01-28 [1] CRAN (R 3.6.1)
 zip            2.0.4    2019-09-01 [1] CRAN (R 3.6.1)

[1] C:/~/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.1/library
Bob

---------------------------------------------------------------------------------
Robert W. Klaver, Unit Leader and Professor
U.S. Geological Survey
Iowa Cooperative Fish and Wildlife Research Unit
Department of Natural Resource Ecology and Management
342 Science II
2310 Pammel Drive
Iowa State University
Ames, Iowa 50011-3221

Phone: 515-294-7639
Fax:       515-294-5468
bklaver@iastate.edu<mailto:bklaver@iastate.edu>

But nature is a stranger yet;
The ones that cite her most
Never have passed her haunted house
Nor simplified her ghost.

To pity those that know her not
Is helped by the regret
That those who know her, know her less
The nearer her they get
                                 E. Dickinson    1877

**Comment by dbspitz** [comment]
Thanks for the prompt response.

I've uploaded a copy of the vignette to github. Hopefully this can help
tide you over until I can locate and fix the underlying issue. One
additional note here: don't be alarmed if running example code yields
different answers than those found in the vignette. Since its release,
there have been major improvements to how migrateR guesses at starting
parameter values in fitting models. (This is the most complicated thing
migrateR does behind the scenes.) This means that some of the results may
differ from those originally noted. Revising the vignette is on the to-do
list, but I haven't yet been able to carve out time to give this the
attention it deserves.

If you run into any other questions or issues, don't hesitate to let me
know!

Best,

Derek

**Comment by bklaver49** [comment]
Thank you very much!

---------------------------------------------------------------------------------
Robert W. Klaver, Unit Leader and Professor
U.S. Geological Survey
Iowa Cooperative Fish and Wildlife Research Unit
Department of Natural Resource Ecology and Management
342 Science II
2310 Pammel Drive
Iowa State University
Ames, Iowa 50011-3221

Phone: 515-294-7639
Fax:       515-294-5468
bklaver@iastate.edu<mailto:bklaver@iastate.edu>

But nature is a stranger yet;
The ones that cite her most
Never have passed her haunted house
Nor simplified her ghost.

To pity those that know her not
Is helped by the regret
That those who know her, know her less
The nearer her they get
                                 E. Dickinson    1877

**Comment by dbspitz** [comment]
The function that caused the hang up with "build_vignettes = T" has been repaired and this option now works with machines tested under v1.0.9.

**Comment by bklaver49** [comment]
Thanks!

---------------------------------------------------------------------------------
Robert W. Klaver, Unit Leader and Professor
U.S. Geological Survey
Iowa Cooperative Fish and Wildlife Research Unit
Department of Natural Resource Ecology and Management
342 Science II
2310 Pammel Drive
Iowa State University
Ames, Iowa 50011-3221

Phone: 515-294-7639
Fax:       515-294-5468
bklaver@iastate.edu<mailto:bklaver@iastate.edu>

But nature is a stranger yet;
The ones that cite her most
Never have passed her haunted house
Nor simplified her ghost.

To pity those that know her not
Is helped by the regret
That those who know her, know her less
The nearer her they get
                                 E. Dickinson    1877
